name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          echo "Building the Calculator App..."
          mkdir -p dist
          cp index.html dist/
          echo "Build complete. Files are in the dist folder."
          
